export interface Review {
  id: number;
  author: string;
  authorAvatar?: string;
  authorPronouns?: string;
  rating: number;
  comment?: string;
}

export type VenueType =
  | "cafe" | "restaurant" | "bar" | "nightclub"
  | "gym" | "studio" | "pool"
  | "library" | "bookstore" | "theatre" | "cinema" | "gallery"
  | "park" | "salon" | "clinic" | "coworking" | "hostel" | "record-store";

// Tag conventions — use these strings consistently:
//   Accessibility:   wheelchair-accessible, step-free, accessible-bathroom,
//                    pool-hoist, automatic-doors, large-print, captions,
//                    adaptive-routes
//   Sensory / ND:    sensory-friendly, low-noise, quiet-space
//   Identity:        lgbtq-owned, lgbtq-affirming, trans-friendly,
//                    trans-affirming, sapphic-owned, bipoc-owned,
//                    bipoc-affirming, women-owned
//   Class / Sober:   sliding-scale, free-entry, alcohol-free, sober-friendly
//   Body:            body-positive
//   Parents/Carers:  chest-feeding-friendly, changing-table-all-genders,
//                    family-bathroom, stroller-accessible, high-chairs,
//                    kids-welcome
export type Tag = string;

export interface Place {
  id: number;
  name: string;
  location: string;
  description?: string;
  imageUrl?: string;
  venueType: VenueType;
  tags: Tag[];
  reviews: Review[];
}

// Author profiles keyed by name; spread into each review for consistency.
const USERS: Record<string, { authorAvatar: string; authorPronouns: string }> = {
  Linnea:  { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Linnea&skinColor=DarkBrown&mouth=Default",     authorPronouns: "she/her"   },
  Erik:    { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Erik&skinColor=Black&mouth=Serious",           authorPronouns: "he/him"    },
  Mira:    { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Mira&skinColor=Brown&mouth=Smile",             authorPronouns: "she/her"   },
  Tobias:  { authorAvatar: "https://api.dicebear.com/9.x/bottts/svg?seed=Tobias",                                          authorPronouns: "he/him"    },
  Jamal:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamal&skinColor=DarkBrown&mouth=Default",      authorPronouns: "he/him"    },
  Sofia:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia&skinColor=Black&mouth=Twinkle",          authorPronouns: "she/her"   },
  Oskar:   { authorAvatar: "https://api.dicebear.com/9.x/pixel-art/svg?seed=Oskar",                                        authorPronouns: "he/him"    },
  Anna:    { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Anna&skinColor=Brown&mouth=Smile",             authorPronouns: "she/her"   },
  Felix:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Felix&skinColor=DarkBrown&mouth=Serious",      authorPronouns: "he/him"    },
  Robin:   { authorAvatar: "https://api.dicebear.com/9.x/shapes/svg?seed=Robin",                                           authorPronouns: "they/them" },
  Charlie: { authorAvatar: "https://api.dicebear.com/9.x/thumbs/svg?seed=Charlie",                                         authorPronouns: "they/them" },
  Marta:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Marta&skinColor=Black&mouth=Default",          authorPronouns: "she/her"   },
  Theo:    { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Theo&skinColor=Brown&mouth=Concerned",         authorPronouns: "he/him"    },
  Lena:    { authorAvatar: "https://api.dicebear.com/9.x/croodles/svg?seed=Lena",                                          authorPronouns: "she/her"   },
  Nadia:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nadia&skinColor=DarkBrown&mouth=Smile",        authorPronouns: "she/her"   },
  Hassan:  { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Hassan&skinColor=Black&mouth=Default",         authorPronouns: "he/him"    },
  Kim:     { authorAvatar: "https://api.dicebear.com/9.x/shapes/svg?seed=Kim",                                             authorPronouns: "they/them" },
  Diego:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Diego&skinColor=Brown&mouth=Tongue",           authorPronouns: "he/him"    },
  Maja:    { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maja&skinColor=Light&mouth=Default",           authorPronouns: "she/her"   },
  Priya:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya&skinColor=Brown&mouth=Default",          authorPronouns: "she/her"   },
  Yusuf:   { authorAvatar: "https://api.dicebear.com/9.x/bottts/svg?seed=Yusuf",                                           authorPronouns: "he/him"    },
  Lukas:   { authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lukas&skinColor=Tanned&mouth=Serious",         authorPronouns: "he/him"    },
  Sam:     { authorAvatar: "https://api.dicebear.com/9.x/pixel-art/svg?seed=Sam",                                          authorPronouns: "they/them" },
};

const placeImage = (photoId: string) =>
  `https://images.unsplash.com/photo-${photoId}?auto=format&fit=crop&w=800&h=600&q=80`;

export const places: Place[] = [
  {
    id: 1,
    name: "Central Cafe",
    location: "Malmö",
    description: "Cozy coffee place in the old town with a steady afternoon crowd.",
    imageUrl: placeImage("1554118811-1e0d58224f24"),
    venueType: "cafe",
    tags: ["wheelchair-accessible", "step-free", "accessible-bathroom", "changing-table-all-genders", "high-chairs", "kids-welcome"],
    reviews: [
      { id: 1, author: "Linnea",  ...USERS.Linnea,  rating: 4, comment: "Step-free entrance round the side, accessible bathroom, and staff who always greet me and my girlfriend warmly. Small things, all of them." },
      { id: 2, author: "Erik",    ...USERS.Erik,    rating: 3, comment: "Crowd skews quite hetero after work. Not unsafe, just not my scene." },
      { id: 3, author: "Mira",    ...USERS.Mira,    rating: 5, comment: "Worked here for hours and nobody so much as glanced at the pronoun pin on my laptop." },
      { id: 4, author: "Tobias",  ...USERS.Tobias,  rating: 2, comment: "Came with my partner. Server seemed visibly thrown when we held hands. Didn't refuse service, just made the meal awkward. Won't be back." },
    ],
  },
  {
    id: 2,
    name: "Fitness Hub",
    location: "Lund",
    description: "Modern training center with a big free-weights area.",
    imageUrl: placeImage("1534438327276-14e5300c3a48"),
    venueType: "gym",
    tags: [],
    reviews: [
      { id: 1, author: "Jamal",   ...USERS.Jamal,   rating: 4, comment: "Equipment is fine. Locker rooms are strictly gendered though, so as a non-binary Black lifter I change in a bathroom stall and try to make myself invisible. The math gets old." },
      { id: 2, author: "Sofia",   ...USERS.Sofia,   rating: 3, comment: "Front desk gendered me correctly without me having to correct anyone. Small win for an otherwise generic gym." },
      { id: 3, author: "Oskar",   ...USERS.Oskar,   rating: 5, comment: "Early mornings are quiet, the music is at a sane volume, and equipment is well-spaced if you use a wheelchair. The 6pm crowd is a different story." },
      { id: 4, author: "Anna",    ...USERS.Anna,    rating: 2, comment: "Got 'ladies, ladies' from a trainer twice during onboarding even after I asked him to stop. Won't be back." },
      { id: 5, author: "Felix",   ...USERS.Felix,   rating: 1, comment: "Trainer 'forgot' my chosen name three times in one session and laughed when I corrected him. The 'forgetting' is the cruelty. Cancelled the membership the next day." },
    ],
  },
  {
    id: 3,
    name: "Stonewall Strength",
    location: "Stockholm",
    description: "LGBTQIA+-owned strength gym in Södermalm. Coached lifts, no judgement, pronouns on staff lanyards, sliding-scale memberships.",
    imageUrl: placeImage("1571902943202-507ec2618e8f"),
    venueType: "gym",
    tags: ["lgbtq-owned", "trans-friendly", "sliding-scale"],
    reviews: [
      { id: 1, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "First gym where I actually felt safe training in my binder. Coaches are excellent." },
      { id: 2, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "The trans-friendly changing room policy is the real deal, not just a sticker on the door." },
      { id: 3, author: "Marta",   ...USERS.Marta,   rating: 4, comment: "Pricey, but the women's lifting collective on Saturdays is the only one I've found where I'm not the only Black lifter in the room. Worth every krona." },
      { id: 4, author: "Theo",    ...USERS.Theo,    rating: 5, comment: "First time I've been coached by another trans guy. Made the difference between dreading deadlifts and loving them." },
      { id: 5, author: "Lena",    ...USERS.Lena,    rating: 2, comment: "Loved the vibe but the front desk made a real mess of my membership. Three months of being charged the wrong rate, three months of nobody returning calls. Sloppy admin for a gym this expensive." },
    ],
  },
  {
    id: 4,
    name: "Saga Coffee House",
    location: "Göteborg",
    description: "Small sapphic-owned cafe near Linnéplatsen. Plants everywhere, vinyl on weekends.",
    imageUrl: placeImage("1453614512568-c4024d13c247"),
    venueType: "cafe",
    tags: ["sapphic-owned", "lgbtq-affirming", "chest-feeding-friendly", "changing-table-all-genders", "high-chairs", "kids-welcome"],
    reviews: [
      { id: 1, author: "Maja",    ...USERS.Maja,    rating: 5, comment: "Felt at home from the second I walked in. They also host a sapphic book club on Sundays." },
      { id: 2, author: "Priya",   ...USERS.Priya,   rating: 4, comment: "Owner asked about my pronouns the second time I came in. Felt seen, not interrogated. Cardamom bun is also unreal." },
      { id: 3, author: "Yusuf",   ...USERS.Yusuf,   rating: 5, comment: "Community board has everything from dyke marches to top-surgery fundraisers, and a corner specifically for Muslim LGBT support groups. The cafe is more than a cafe." },
      { id: 4, author: "Lukas",   ...USERS.Lukas,   rating: 2, comment: "Coffee is good but a regular cornered me to lecture me about being a 'good ally' for fifteen minutes. The owner watched and didn't intervene. Won't be back." },
    ],
  },
  {
    id: 5,
    name: "Boulder Bee Studio",
    location: "Malmö",
    description: "Bouldering gym with a strong LGBTQIA+ and disability-inclusive climbing community. Adaptive routes set monthly; weekly beginner sessions.",
    imageUrl: placeImage("1547036967-23d11aacaee0"),
    venueType: "gym",
    tags: ["lgbtq-affirming", "wheelchair-accessible", "adaptive-routes"],
    reviews: [
      { id: 1, author: "Mira",    ...USERS.Mira,    rating: 5, comment: "Pride climb night on Wednesdays is the highlight of my week. The community here is unmatched." },
      { id: 2, author: "Erik",    ...USERS.Erik,    rating: 3, comment: "Routes get reset way less often than they should and the chalk situation is grim. Community is great, facility is mid." },
      { id: 3, author: "Linnea",  ...USERS.Linnea,  rating: 5, comment: "Showed up alone after top surgery looking for a low-impact return to movement. Staff helped me find easy routes without making it weird." },
      { id: 4, author: "Hassan",  ...USERS.Hassan,  rating: 4, comment: "Wall isn't huge but the trans climbers' chat group means I always have a belay partner. The adaptive routes the setters added last month were a revelation." },
    ],
  },
  {
    id: 6,
    name: "Tango House",
    location: "Stockholm",
    description: "Dance studio teaching Argentine tango with traditional and same-sex milongas. No fixed lead/follow roles. Wheelchair-accessible floor.",
    imageUrl: placeImage("1547153760-18fc86324498"),
    venueType: "studio",
    tags: ["lgbtq-affirming", "wheelchair-accessible"],
    reviews: [
      { id: 1, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "Same-sex milonga on Fridays is the only place I've found where I can dance both roles without explaining myself." },
      { id: 2, author: "Marta",   ...USERS.Marta,   rating: 4, comment: "Teachers are technical but never strict about gendered roles, and they coach poses that work for the body in front of them. Refreshing." },
      { id: 3, author: "Kim",     ...USERS.Kim,     rating: 5, comment: "First time leading another woman in tango and feeling like nobody in the room thought it was strange. Cried a little." },
      { id: 4, author: "Theo",    ...USERS.Theo,    rating: 2, comment: "Love the inclusive concept but the venue is genuinely dirty. Bathrooms looked like they hadn't been cleaned in weeks. Tango is great, basic hygiene is not." },
    ],
  },
  {
    id: 7,
    name: "Sportbar Tre Kronor",
    location: "Göteborg",
    description: "Classic sports bar near the stadium. Beer on tap, every match on the screens.",
    imageUrl: placeImage("1546726747-421c6d69c929"),
    venueType: "bar",
    tags: [],
    reviews: [
      { id: 1, author: "Erik",    ...USERS.Erik,    rating: 1, comment: "Got refused service after a bartender clocked me holding hands with my partner. Manager apologised the next day but the damage was done. Stay away." },
      { id: 2, author: "Oskar",   ...USERS.Oskar,   rating: 3, comment: "Crowd is overwhelmingly straight dudes. Food is fine, vibes are not for everyone." },
      { id: 3, author: "Jamal",   ...USERS.Jamal,   rating: 4, comment: "Staff is friendly and didn't misgender me when I corrected them. That's all I ask of a sports bar." },
      { id: 4, author: "Felix",   ...USERS.Felix,   rating: 2, comment: "Got called a slur by a drunk regular after the derby. Staff did intervene, but I'm not going back." },
    ],
  },
  {
    id: 8,
    name: "Northern CrossFit",
    location: "Lund",
    description: "CrossFit box with morning and evening classes. Welcomes all levels but expect a real workout.",
    imageUrl: placeImage("1583454110551-21f2fa2afe61"),
    venueType: "gym",
    tags: [],
    reviews: [
      { id: 1, author: "Sofia",   ...USERS.Sofia,   rating: 4, comment: "Coaches say 'athletes' instead of 'ladies', which sounds small until you've been the only AFAB person in the box and it lands hard." },
      { id: 2, author: "Anna",    ...USERS.Anna,    rating: 3, comment: "Community is solid but the music level at 6pm makes my migraines worse. Morning class is much chiller, headphones not required." },
      { id: 3, author: "Diego",   ...USERS.Diego,   rating: 5, comment: "Coaches took my chest binder seriously when they programmed scaling for me. First box that's done that without me asking three times. Also: I'm the only Latine person here and they didn't make it weird." },
      { id: 4, author: "Lukas",   ...USERS.Lukas,   rating: 1, comment: "Coaches preach inclusion on Instagram and call women 'sweetheart' in class. Either the bio is wrong or the coaches don't read it. Quit after two months. Refund request ignored." },
    ],
  },
  {
    id: 9,
    name: "Stonewall Library",
    location: "Stockholm",
    description: "Public library with one of the largest LGBTQIA+ collections in the Nordics. Pronoun pins at the front desk, step-free entrance, large-print and audiobook options.",
    imageUrl: placeImage("1481627834876-b7833e8f5570"),
    venueType: "library",
    tags: ["lgbtq-affirming", "step-free", "automatic-doors", "large-print", "free-entry", "family-bathroom", "stroller-accessible", "kids-welcome", "changing-table-all-genders"],
    reviews: [
      { id: 1, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "First public library I've been in where the LGBTQ+ shelf isn't tucked away. It's front and centre." },
      { id: 2, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "Quiet, well-lit, automatic doors at the entrance, librarians wear pronoun pins. Best afternoon refuge in the city for a wheelchair user who needs predictable spaces." },
      { id: 3, author: "Marta",   ...USERS.Marta,   rating: 4, comment: "Excellent lesbian history section, and the Black queer reading list curated for last year's Pride is still on display. Wifi is patchy near the windows." },
      { id: 4, author: "Theo",    ...USERS.Theo,    rating: 5, comment: "Used the gender-neutral bathroom three times in one visit because I could. Small joy." },
      { id: 5, author: "Lena",    ...USERS.Lena,    rating: 2, comment: "Collection is great in theory, but half the books I tried to borrow were 'lost in transit' or never returned. Catalogue listings are from 2019. The intention is there; the funding clearly isn't." },
    ],
  },
  {
    id: 10,
    name: "The Common Stage",
    location: "Stockholm",
    description: "Community theatre in a converted warehouse. Cheap tickets, BYO snacks, productions that take risks. Captioned performances on Sundays.",
    imageUrl: placeImage("1503095396549-807759245b35"),
    venueType: "theatre",
    tags: ["captions", "lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Maja",    ...USERS.Maja,    rating: 5, comment: "Saw a sapphic reimagining of A Midsummer Night's Dream here. Staff gave me a free programme when they saw I came alone." },
      { id: 2, author: "Lukas",   ...USERS.Lukas,   rating: 4, comment: "Tiny venue with big heart. Productions uneven, energy unmatched. The post-show Q&A was the most thoughtful conversation I've had all year." },
      { id: 3, author: "Marta",   ...USERS.Marta,   rating: 5, comment: "Trans actor played the lead. No big announcement, just casting. That's how it should be." },
      { id: 4, author: "Priya",   ...USERS.Priya,   rating: 2, comment: "Saw a piece about LGBT migration written by someone who'd clearly never met one. Earnest, condescending, and two and a half hours long. Left at intermission." },
    ],
  },
  {
    id: 11,
    name: "The Mira Hub",
    location: "Stockholm",
    description: "Co-working space in Vasastan with quiet desks, phone-booth rooms, pronouns on staff name badges, and a sensory-friendly hour every weekday morning.",
    imageUrl: placeImage("1497366754035-f200968a6e72"),
    venueType: "coworking",
    tags: ["sensory-friendly", "wheelchair-accessible", "lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Robin",   ...USERS.Robin,   rating: 4, comment: "Quiet desks, hot-desk pricing, pronouns on staff name badges. As a freelancer mid-transition, that matters." },
      { id: 2, author: "Sam",     ...USERS.Sam,     rating: 5, comment: "Best phone-booth rooms in the city. As an autistic adult with ADHD I get my best work done here." },
      { id: 3, author: "Sofia",   ...USERS.Sofia,   rating: 4, comment: "Coffee is decent, snacks are free, all-gender bathroom is the cleanest in any office I've been in, and the lift is reliable." },
      { id: 4, author: "Lukas",   ...USERS.Lukas,   rating: 1, comment: "Paid for an annual membership up-front and they changed the pricing structure two months in, no refund offered. Customer service is a chatbot that loops. Avoid the annual plan at all costs." },
    ],
  },
  {
    id: 12,
    name: "Folkbadet",
    location: "Malmö",
    description: "Public swimming hall with weekly trans-friendly hours, family changing rooms with private cubicles, working pool hoist, and larger swimsuits in stock.",
    imageUrl: placeImage("1530549387789-4c1017266635"),
    venueType: "pool",
    tags: ["trans-affirming", "pool-hoist", "wheelchair-accessible", "family-bathroom", "changing-table-all-genders", "stroller-accessible", "kids-welcome"],
    reviews: [
      { id: 1, author: "Theo",    ...USERS.Theo,    rating: 5, comment: "Trans-friendly swim hours on Thursdays changed my relationship with my body. Hadn't been in a pool in eight years before this." },
      { id: 2, author: "Felix",   ...USERS.Felix,   rating: 5, comment: "Family changing rooms with private cubicles for everyone. As a trans guy I finally got to swim without dread." },
      { id: 3, author: "Linnea",  ...USERS.Linnea,  rating: 4, comment: "Public pool doing the basic thing — making everyone safe — better than any private gym I've been to. Pool hoist works, and nobody side-eyed my fat body in the changing room." },
      { id: 4, author: "Mira",    ...USERS.Mira,    rating: 2, comment: "Inclusive hours are excellent on paper, but one regular lifeguard misgendered me three sessions in a row. Reported it twice, nothing changed. Switched to a different pool." },
    ],
  },
  {
    id: 13,
    name: "Vinyl Lab Records",
    location: "Göteborg",
    description: "Independent record store with one of the best LGBTQIA+-music sections in Sweden. In-store shows on Tuesdays, signed releases by trans and disabled artists.",
    imageUrl: placeImage("1483412033650-1015ddeb83d1"),
    venueType: "record-store",
    tags: ["lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Tobias",  ...USERS.Tobias,  rating: 5, comment: "Best curated LGBTQIA+ section in Sweden. The owner knows every release by heart and stocks pressings from disabled artists you won't find elsewhere." },
      { id: 2, author: "Maja",    ...USERS.Maja,    rating: 4, comment: "Sat on the floor flipping records for two hours. Owner brought me coffee. Found a Tracy Chapman pressing I'd been hunting for." },
      { id: 3, author: "Erik",    ...USERS.Erik,    rating: 3, comment: "Owner is lovely but the pricing is steep — twice the going rate on a few pressings I checked. The 'LGBT section' is also half-mainstream pop. Mixed feelings." },
      { id: 4, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "Hosts in-store performances. Saw a sapphic punk band on a Tuesday and felt like I was eighteen again." },
    ],
  },
  {
    id: 14,
    name: "Velvet Lounge",
    location: "Stockholm",
    description: "Cocktail bar in Södermalm with weekly drag nights and a famously good vermouth list.",
    imageUrl: placeImage("1514933651103-005eec06c04b"),
    venueType: "bar",
    tags: ["lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Nadia",   ...USERS.Nadia,   rating: 5, comment: "Saturday drag brunch is iconic. Hugged the host on the way out. They sell out two weeks in advance, book ahead." },
      { id: 2, author: "Hassan",  ...USERS.Hassan,  rating: 4, comment: "Bartenders are kind to everyone and the drag queens get a free shot from the kitchen between sets. That detail says it all." },
      { id: 3, author: "Kim",     ...USERS.Kim,     rating: 5, comment: "One of the few places in town where I never have to explain who I am." },
      { id: 4, author: "Diego",   ...USERS.Diego,   rating: 3, comment: "Drinks are great but the regulars are tight-knit. Took me three visits before anyone made eye contact. Worth it once they did." },
    ],
  },
  {
    id: 15,
    name: "Iron Garden",
    location: "Stockholm",
    description: "24/7 industrial-style gym in Hammarby Sjöstad. Mixed crowd, techno on the speakers, no mirrors in the free-weights area.",
    imageUrl: placeImage("1591291621164-2c6367723315"),
    venueType: "gym",
    tags: [],
    reviews: [
      { id: 1, author: "Sam",     ...USERS.Sam,     rating: 4, comment: "Open 24/7 means I can train when the place is half-empty. As an AFAB lifter tired of catcalls and unsolicited form tips, this is everything." },
      { id: 2, author: "Lena",    ...USERS.Lena,    rating: 3, comment: "Mixed crowd, but it leans hetero-bro after 7pm. Earlier in the day it's lovely and quiet." },
      { id: 3, author: "Felix",   ...USERS.Felix,   rating: 5, comment: "Nobody bothered me once they saw the testosterone shot in my locker. Big-city anonymity in the best way." },
      { id: 4, author: "Mira",    ...USERS.Mira,    rating: 2, comment: "Showers are filthy and the air conditioning hasn't worked in months. Vibes are fine, hygiene is not." },
    ],
  },
  {
    id: 16,
    name: "Sober Sundays",
    location: "Malmö",
    description: "Alcohol-free bar and cafe in Möllevången with LGBT-friendly programming and mocktail flights.",
    imageUrl: placeImage("1559925393-8be0ec4767c8"),
    venueType: "cafe",
    tags: ["alcohol-free", "sober-friendly", "lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "Finally an LGBT space that doesn't revolve around drinking. Game nights are a riot." },
      { id: 2, author: "Tobias",  ...USERS.Tobias,  rating: 4, comment: "Came as a sober gay man and finally felt like both parts of me belonged in one room. Rare combo to find." },
      { id: 3, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "As someone in recovery this place is a lifeline." },
      { id: 4, author: "Anna",    ...USERS.Anna,    rating: 1, comment: "Booked a table for ten for my birthday. Showed up to find it given to walk-ins. Owner shrugged. Spent my birthday standing." },
    ],
  },
  {
    id: 17,
    name: "Pride Lift Club",
    location: "Stockholm",
    description: "LGBTQIA+ powerlifting club in Hägersten. Beginner-friendly intake, coached meets, women's and trans-only hours.",
    imageUrl: placeImage("1540497077202-7c8a3999166f"),
    venueType: "gym",
    tags: ["lgbtq-owned", "trans-friendly", "trans-affirming"],
    reviews: [
      { id: 1, author: "Theo",    ...USERS.Theo,    rating: 5, comment: "Hit my first competition platform here. The coaches treated me like an athlete from day one, not a trans athlete." },
      { id: 2, author: "Marta",   ...USERS.Marta,   rating: 5, comment: "Women's and trans-only hours are non-negotiable for me and they're protected here. Game changer." },
      { id: 3, author: "Jamal",   ...USERS.Jamal,   rating: 4, comment: "Pricey, but it's the only gym where my trans flag patch on my bag has never gotten a side-eye." },
      { id: 4, author: "Kim",     ...USERS.Kim,     rating: 5, comment: "First gym I've ever been to where the music doesn't make me want to leave, and the locker room doesn't make me brace." },
      { id: 5, author: "Sofia",   ...USERS.Sofia,   rating: 2, comment: "Programming is great but a new coach hired six months ago dead-named me twice and didn't apologise the second time. Management told me to 'give him time'. Not coming back unless he's gone." },
    ],
  },
  {
    id: 18,
    name: "The Locker Room",
    location: "Göteborg",
    description: "Old-school commercial gym near Avenyn. Loud, busy, lots of CrossFit-adjacent regulars.",
    imageUrl: placeImage("1568901346375-23c9450c58cd"),
    venueType: "gym",
    tags: [],
    reviews: [
      { id: 1, author: "Oskar",   ...USERS.Oskar,   rating: 3, comment: "It's just a gym. Lots of cis straight guys, but they mostly mind their own if you do too." },
      { id: 2, author: "Diego",   ...USERS.Diego,   rating: 4, comment: "Equipment is great. The 'lads lads lads' energy means I keep my pronoun pin off my gym bag here." },
      { id: 3, author: "Anna",    ...USERS.Anna,    rating: 2, comment: "Got eye-rolled at the squat rack by two guys who clearly thought I shouldn't be there. Off-peak is fine; peak hours are exhausting." },
      { id: 4, author: "Felix",   ...USERS.Felix,   rating: 4, comment: "Anonymity works for me as a trans guy passing in public. Nobody talks to anyone. Take that as you will." },
    ],
  },
  {
    id: 19,
    name: "Estudio Verde",
    location: "Malmö",
    description: "Yoga studio near Möllevångstorget with an explicit body-positive, LGBTQIA+-affirming policy. Fat-friendly props and chair-yoga classes weekly.",
    imageUrl: placeImage("1545205597-3d9d02c29597"),
    venueType: "studio",
    tags: ["lgbtq-affirming", "body-positive", "chest-feeding-friendly"],
    reviews: [
      { id: 1, author: "Priya",   ...USERS.Priya,   rating: 5, comment: "Teachers actually mean it when they say 'this pose looks however your body needs it to'." },
      { id: 2, author: "Sam",     ...USERS.Sam,     rating: 5, comment: "Neutral language throughout — 'lift your chest' not 'show your chest', no 'ladies' calls. Tiny details, huge difference." },
      { id: 3, author: "Charlie", ...USERS.Charlie, rating: 4, comment: "Drop-in is fair and there's a quiet trans-affirming Friday class that's helped me reconnect with my body." },
      { id: 4, author: "Yusuf",   ...USERS.Yusuf,   rating: 4, comment: "Small studio, very kind teachers, never any awkward gendered partner work. Book a few days ahead." },
    ],
  },
  {
    id: 20,
    name: "Bar Provence",
    location: "Stockholm",
    description: "Classic wine bar in Östermalm. Tight list of French naturals, no-frills service.",
    imageUrl: placeImage("1510812431401-41d2bd2722f3"),
    venueType: "bar",
    tags: [],
    reviews: [
      { id: 1, author: "Sofia",   ...USERS.Sofia,   rating: 4, comment: "Came with my girlfriend for our anniversary. Polite, no-fuss service — the bare minimum elsewhere, but here it felt like respect." },
      { id: 2, author: "Tobias",  ...USERS.Tobias,  rating: 3, comment: "Felt invisible in the best and worst way. Wine is great. Don't expect them to chat." },
      { id: 3, author: "Lena",    ...USERS.Lena,    rating: 5, comment: "Owner didn't bat an eye at me and my partner being a same-gender couple. As a couple in our sixties we've experienced the spectrum; this was the quietly affirming end of it." },
    ],
  },
  {
    id: 21,
    name: "Café Bechdel",
    location: "Malmö",
    description: "Feminist and LGBT cafe in Möllevången. Books on the walls, zines on the counter, no laptops after 4pm.",
    imageUrl: placeImage("1507842217343-583bb7270b66"),
    venueType: "cafe",
    tags: ["lgbtq-affirming", "women-owned", "chest-feeding-friendly", "changing-table-all-genders", "kids-welcome"],
    reviews: [
      { id: 1, author: "Mira",    ...USERS.Mira,    rating: 5, comment: "Reading corner is my happy place. They stock zines you can't find anywhere else." },
      { id: 2, author: "Charlie", ...USERS.Charlie, rating: 4, comment: "Met half my chosen family at the Sunday lesbian book club they host. Cafe is more like a living room." },
      { id: 3, author: "Nadia",   ...USERS.Nadia,   rating: 5, comment: "Coffee is good, but the real draw is the conversations you accidentally end up in." },
      { id: 4, author: "Hassan",  ...USERS.Hassan,  rating: 1, comment: "Got hit with a 'you don't really get the feminist project, do you' from a regular when I dared to disagree about a book. The owner laughed. As a man of colour walking into a 'feminist' space, the gatekeeping was loud. Won't be back." },
    ],
  },
  {
    id: 22,
    name: "Marais Coffee",
    location: "Stockholm",
    description: "Tiny espresso bar in Södermalm, named after Paris's gay quarter. Locals, tourists, drag queens between gigs.",
    imageUrl: placeImage("1517022812141-23620dba5c23"),
    venueType: "cafe",
    tags: ["lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Yusuf",   ...USERS.Yusuf,   rating: 5, comment: "Owner remembers regulars by pronoun, not just name. In the heart of Stockholm's gay quarter, exactly as it should be." },
      { id: 2, author: "Lena",    ...USERS.Lena,    rating: 4, comment: "Standing room only most days but it's the best people-watching in Söder. Saw three first dates and one breakup in one visit." },
      { id: 3, author: "Priya",   ...USERS.Priya,   rating: 5, comment: "Friendly, LGBT-friendly, fast. Exactly what a neighbourhood espresso bar should be." },
    ],
  },
  {
    id: 23,
    name: "FlowMotion Yoga",
    location: "Göteborg",
    description: "Big multi-room yoga studio near Linnéplatsen. Vinyasa, yin, prenatal, and a weekly LGBT-led class.",
    imageUrl: placeImage("1588286840104-8957b019727f"),
    venueType: "studio",
    tags: ["lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Sam",     ...USERS.Sam,     rating: 4, comment: "Solid teachers across the board. The LGBT-led Thursday class is its own little world and the reason I keep my membership." },
      { id: 2, author: "Tobias",  ...USERS.Tobias,  rating: 3, comment: "Big-studio assembly-line vibes in the main classes. Find an inclusive teacher and stick with them." },
      { id: 3, author: "Maja",    ...USERS.Maja,    rating: 4, comment: "Gender-neutral changing room is a single small cubicle, so expect a wait. Once you're in, the studio itself is great." },
      { id: 4, author: "Felix",   ...USERS.Felix,   rating: 5, comment: "Yin Sunday saved my back after months of binding. Teacher checked in about my body without making it a Thing." },
    ],
  },
  {
    id: 24,
    name: "Spike Volleyball Bar",
    location: "Göteborg",
    description: "Beach-volleyball-themed bar on Hisingen. Sand court out back, mostly straight crowd, lively atmosphere.",
    imageUrl: placeImage("1592656094267-764a45160876"),
    venueType: "bar",
    tags: [],
    reviews: [
      { id: 1, author: "Diego",   ...USERS.Diego,   rating: 4, comment: "Drop-in volleyball league was way more welcoming than I expected for a straight sports bar. Mixed teams, no weird vibes." },
      { id: 2, author: "Anna",    ...USERS.Anna,    rating: 3, comment: "Fun for a group of friends, but my partner and I got plenty of stares as a same-gender couple. Tolerable, not affirming." },
      { id: 3, author: "Erik",    ...USERS.Erik,    rating: 2, comment: "Sand court is great in theory. In practice it's full of broken glass on Saturday mornings because nobody cleans up after Friday. Played one game, got a cut, left." },
    ],
  },
  {
    id: 25,
    name: "Lavender Lifts",
    location: "Malmö",
    description: "LGBTQIA+-owned strength and conditioning gym in Värnhem. Coached only, small classes, sliding-scale membership.",
    imageUrl: placeImage("1611162616305-c69b3fa7fbe0"),
    venueType: "gym",
    tags: ["lgbtq-owned", "sliding-scale", "trans-friendly"],
    reviews: [
      { id: 1, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "Sliding-scale membership made it possible for me to train consistently for the first time in years." },
      { id: 2, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "Coaches asked what my goals were, not what my body's goals were. Eleven years of lifting and this is the first place that's happened." },
      { id: 3, author: "Kim",     ...USERS.Kim,     rating: 4, comment: "Class caps mean the whole LGBT crew there knows each other. Small space, big chosen-family energy." },
      { id: 4, author: "Nadia",   ...USERS.Nadia,   rating: 5, comment: "Left my first class feeling lighter, not just sorer. Turns out training in an un-misgendered room changes things." },
      { id: 5, author: "Marta",   ...USERS.Marta,   rating: 4, comment: "Wish for more open-gym hours, but the coached programming is genuinely the best in the city." },
    ],
  },
  {
    id: 26,
    name: "Solidaridad Kitchen",
    location: "Stockholm",
    description: "Latin American restaurant in Skanstull run by an LGBT couple. Ceviche, arepas, and a Pride flag behind the bar.",
    imageUrl: placeImage("1565299624946-b28f40a0ae38"),
    venueType: "restaurant",
    tags: ["lgbtq-owned", "bipoc-owned", "high-chairs", "kids-welcome"],
    reviews: [
      { id: 1, author: "Priya",   ...USERS.Priya,   rating: 5, comment: "Ceviche better than anything I had in Lima last year. They sat me at the bar when I came in alone." },
      { id: 2, author: "Sam",     ...USERS.Sam,     rating: 4, comment: "LGBT-owned and it shows in every detail — the music, the menu notes, the way the staff treats everyone." },
      { id: 3, author: "Diego",   ...USERS.Diego,   rating: 5, comment: "Brought my novio and the server wished us a beautiful evening without skipping a beat. The arepas are reason enough." },
      { id: 4, author: "Yusuf",   ...USERS.Yusuf,   rating: 4, comment: "Loud and full of joy. Ended up sharing a table with a drag queen between sets at a nearby bar." },
    ],
  },
  {
    id: 27,
    name: "Page & Pride Bookstore",
    location: "Uppsala",
    description: "Independent LGBT bookstore in central Uppsala with a curated rainbow children's section and a weekly poetry night.",
    imageUrl: placeImage("1521587760476-6c12a4b040da"),
    venueType: "bookstore",
    tags: ["lgbtq-owned", "lgbtq-affirming", "chest-feeding-friendly", "family-bathroom", "kids-welcome"],
    reviews: [
      { id: 1, author: "Mira",    ...USERS.Mira,    rating: 5, comment: "Three trans memoirs I couldn't get anywhere else. Staff recommendations are next-level." },
      { id: 2, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "Monthly LGBT poetry night. I read here for the first time. The crowd was kind." },
      { id: 3, author: "Erik",    ...USERS.Erik,    rating: 4, comment: "Small but every shelf is curated with care. Children's section has rainbow families." },
      { id: 4, author: "Anna",    ...USERS.Anna,    rating: 4, comment: "Came in for one book, left with five. Staff just gets it." },
    ],
  },
  {
    id: 28,
    name: "Cinéma du Coin",
    location: "Stockholm",
    description: "Two-screen arthouse cinema in Vasastan. Monthly LGBT film festival, captioned screenings, and a small bar in the lobby.",
    imageUrl: placeImage("1489599849927-2ee91cede3ba"),
    venueType: "cinema",
    tags: ["captions", "lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Lena",    ...USERS.Lena,    rating: 4, comment: "Monthly LGBT film festival is the highlight of my Stockholm calendar. Seats creak; the curation is gold." },
      { id: 2, author: "Diego",   ...USERS.Diego,   rating: 5, comment: "Watched a Pedro Almodóvar retrospective here over a weekend. Cried in public, no one made it weird." },
      { id: 3, author: "Sofia",   ...USERS.Sofia,   rating: 4, comment: "Tiny theatre with character. Bring a cushion. Worth it for the rare prints they show." },
      { id: 4, author: "Tobias",  ...USERS.Tobias,  rating: 5, comment: "First place I saw a film where the trans character wasn't tragic. Post-screening discussion was genuine, not performative." },
    ],
  },
  {
    id: 29,
    name: "Pride Health",
    location: "Stockholm",
    description: "LGBTQIA+-affirming community health clinic in Telefonplan. GP services, free STI testing, trans-affirming care, trauma-informed staff.",
    imageUrl: placeImage("1576091160399-112ba8d25d1d"),
    venueType: "clinic",
    tags: ["lgbtq-affirming", "trans-affirming", "wheelchair-accessible"],
    reviews: [
      { id: 1, author: "Felix",   ...USERS.Felix,   rating: 5, comment: "First GP who didn't flinch when I explained my body. Genuinely helped me transition my care." },
      { id: 2, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "Free STI testing without a single intrusive question. The intake form has pronouns and chosen name fields up top." },
      { id: 3, author: "Kim",     ...USERS.Kim,     rating: 4, comment: "Wait times can be long but every staff member is trauma-informed. Worth it." },
      { id: 4, author: "Sam",     ...USERS.Sam,     rating: 5, comment: "Reception called me by my chosen name before I even asked. Cried in the waiting room. Good cry." },
      { id: 5, author: "Hassan",  ...USERS.Hassan,  rating: 2, comment: "Care is excellent once you're in. Getting in is months. The waitlist for trans care is over a year. Nobody's fault here is the clinic's, but the system is failing the people this place is built to serve." },
    ],
  },
  {
    id: 30,
    name: "Studio Trim",
    location: "Stockholm",
    description: "Gender-neutral hair salon in Södermalm. Flat-rate pricing by service, not by gender. No assumptions made at the chair.",
    imageUrl: placeImage("1562322140-8baeececf3df"),
    venueType: "salon",
    tags: ["lgbtq-affirming", "trans-affirming"],
    reviews: [
      { id: 1, author: "Charlie", ...USERS.Charlie, rating: 5, comment: "Flat-rate pricing regardless of length or gender. First salon I haven't dreaded in a decade." },
      { id: 2, author: "Theo",    ...USERS.Theo,    rating: 5, comment: "Asked what I wanted, not what they thought I needed. Walked out with the haircut I'd been describing for years." },
      { id: 3, author: "Maja",    ...USERS.Maja,    rating: 4, comment: "Stylists listen. The undercut I asked for was the undercut I got." },
      { id: 4, author: "Hassan",  ...USERS.Hassan,  rating: 4, comment: "Music is good, vibes are inclusive, no awkward small talk about wives or girlfriends." },
    ],
  },
  {
    id: 31,
    name: "House of Glitter",
    location: "Stockholm",
    description: "LGBTQIA+ nightclub at Slussen. Mixed-night programming, gender-neutral bathrooms, step-free entrance, door staff that genuinely watch out for you.",
    imageUrl: placeImage("1545128485-c400e7702796"),
    venueType: "nightclub",
    tags: ["lgbtq-affirming", "wheelchair-accessible", "step-free"],
    reviews: [
      { id: 1, author: "Nadia",   ...USERS.Nadia,   rating: 5, comment: "Wednesday lesbian nights are sacred. Door staff is firm but kind. Security will walk you to your Uber." },
      { id: 2, author: "Diego",   ...USERS.Diego,   rating: 4, comment: "Best dance floor since Madrid. The crowd is mixed, the music is inclusive, the bathroom queue is chaos in the best way." },
      { id: 3, author: "Robin",   ...USERS.Robin,   rating: 5, comment: "Gender-neutral bathrooms with full-length stalls. Step-free entrance and a viewing platform that doesn't require stairs. After ten years of clubbing I finally feel like I belong on the dance floor." },
      { id: 4, author: "Anna",    ...USERS.Anna,    rating: 4, comment: "Cover is steep, drinks are reasonable, security genuinely cares. Felt safer here than at most 'mainstream' clubs." },
    ],
  },
  {
    id: 32,
    name: "Modern Art Forum",
    location: "Göteborg",
    description: "Small contemporary art gallery focused on LGBT and diaspora artists. Free entry on first Thursdays. Sensory-friendly viewing hours twice a month.",
    imageUrl: placeImage("1531058020387-3be344556be6"),
    venueType: "gallery",
    tags: ["lgbtq-affirming", "bipoc-affirming", "sensory-friendly", "free-entry", "stroller-accessible", "kids-welcome"],
    reviews: [
      { id: 1, author: "Sam",     ...USERS.Sam,     rating: 5, comment: "Current exhibition is entirely Black LGBT artists. The curation is fearless and the wall texts don't apologise for the work." },
      { id: 2, author: "Yusuf",   ...USERS.Yusuf,   rating: 4, comment: "Quiet, free entry one Thursday a month, and the guard is the most patient art-explainer in Göteborg." },
      { id: 3, author: "Mira",    ...USERS.Mira,    rating: 5, comment: "Sat in front of one piece for forty minutes during the sensory-friendly hour. No one rushed me. The bench was placed exactly where it should be." },
      { id: 4, author: "Hassan",  ...USERS.Hassan,  rating: 3, comment: "Smaller than I expected and the cafe is overpriced. But the gallery itself? Worth the visit." },
    ],
  },
  {
    id: 33,
    name: "Sankt Hans Park",
    location: "Lund",
    description: "Large urban park that hosts LGBT skate meets, summer drag picnics, and a weekly community market.",
    imageUrl: placeImage("1500382017468-9049fed747ef"),
    venueType: "park",
    tags: ["lgbtq-affirming", "free-entry", "stroller-accessible", "kids-welcome", "family-bathroom"],
    reviews: [
      { id: 1, author: "Erik",    ...USERS.Erik,    rating: 5, comment: "Sunday drag picnics in summer turn this park into the best public space in Lund." },
      { id: 2, author: "Anna",    ...USERS.Anna,    rating: 4, comment: "Big enough to find a quiet corner, central enough to walk to. Felt safe even after dark — rare." },
      { id: 3, author: "Felix",   ...USERS.Felix,   rating: 4, comment: "Cycled here for the LGBT skate meet. Found my people on a Wednesday at six. Now I come every week." },
      { id: 4, author: "Linnea",  ...USERS.Linnea,  rating: 5, comment: "Picnicked with my girlfriend, no stares, just dogs and other queers and the smell of grass." },
    ],
  },
  {
    id: 34,
    name: "La Cantine",
    location: "Göteborg",
    description: "LGBT-owned bistro near Linnéplatsen. Lyonnaise classics, a thoughtful vegan option, two-hour dinners welcome.",
    imageUrl: placeImage("1517248135467-4c7edcad34c4"),
    venueType: "restaurant",
    tags: ["lgbtq-owned", "high-chairs", "kids-welcome", "family-bathroom"],
    reviews: [
      { id: 1, author: "Diego",   ...USERS.Diego,   rating: 5, comment: "Came alone, ended up chatting with the chef about her partner's home cooking. Duck confit is reason enough to return." },
      { id: 2, author: "Lena",    ...USERS.Lena,    rating: 4, comment: "Lyonnaise classics. LGBT owner with a rainbow sticker on the door and a Pride flag behind the bar." },
      { id: 3, author: "Priya",   ...USERS.Priya,   rating: 5, comment: "Vegan option that's actually thoughtful, not a sad salad. Brought my parents and they cried over the dessert." },
      { id: 4, author: "Jamal",   ...USERS.Jamal,   rating: 1, comment: "Two hours on the waiting list with a reservation, then seated at a table next to the bathroom. Server forgot two of our orders. The 'LGBT-owned' bit doesn't excuse the service. Disappointing." },
    ],
  },
  {
    id: 35,
    name: "Rainbow Hostel",
    location: "Stockholm",
    description: "LGBTQ+ hostel near Centralen. Gender-inclusive dorm option, weekly LGBT mixers in the common room.",
    imageUrl: placeImage("1568495248636-6432b97bd949"),
    venueType: "hostel",
    tags: ["lgbtq-owned", "lgbtq-affirming"],
    reviews: [
      { id: 1, author: "Sam",     ...USERS.Sam,     rating: 5, comment: "Three nights as a non-binary solo traveller. The dorms have a gender-inclusive option and the staff meant it." },
      { id: 2, author: "Charlie", ...USERS.Charlie, rating: 4, comment: "Common room hosts LGBT mixers twice a week. Made friends I'll see again. Beds firm, walls thin, vibe is everything." },
      { id: 3, author: "Yusuf",   ...USERS.Yusuf,   rating: 5, comment: "Owner is a trans guy who's been backpacking for thirty years. His tips for safe travel were better than any guidebook." },
      { id: 4, author: "Nadia",   ...USERS.Nadia,   rating: 3, comment: "Wifi is bad and bathrooms are shared. For the price and the community though, I'd come back tomorrow." },
    ],
  },
];
